name: NodeJS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - run: sudo chown -R $USER:$USER /home/azureuser/actions-runner/_work/Albatross
      - uses: actions/checkout@v2
        with:
          clean: "false"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Stop Albatross
        run: |
          sudo pm2 stop albatross

      - name: Build
        run: |
          sudo yarn install
          sudo yarn build

      - name: Start
        run: |
          sudo pm2 restart albatross
