name: NodeJS

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - run: sudo chown -R $USER:$USER /home/azureuser/actions-runner/_work/Albatross
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          sudo yarn install
          sudo yarn build

      - name: Create .env file
        run: |
          sudo touch.env
          sudo echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          sudo echo GUILD_ID=${{ secrets.GUILD_ID }} >> .env
          sudo echo TOKEN=${{ secrets.TOKEN }} >> .env
          sudo echo YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }} >> .env
          sudo echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
          sudo echo TENOR_GIF_KEY=${{ secrets.TENOR_GIF_KEY }} >> .env

      - name: Start
        run: |
          sudo yarn start
